name: econoscope
region: nyc

services:
  - name: api
    source_dir: dashboard/backend
    environment_slug: python
    http_port: 8000
    run_command: uvicorn main:app --host 0.0.0.0 --port 8000
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

  - name: dashboard
    source_dir: dashboard/frontend
    environment_slug: node-js
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
